version: '3.4'

services:
  react:
    image: react
    build:
      context: my-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
